### ISSUE TITLE
Ability to select multiple or single image

### ISSUE THREAD

**Issue by DavidCorrado** [guillermomuntaner/GMImagePicker#17]
I dont believe this is built in.  It would be useful.  If single is selected.  When you choose one image it auto selects that.  If you want a standard UI then you should do this.

**Comment by guillermomuntaner** [comment]
Hi. You are right, the project started as a simple "Multiple image picker" but then I started adding other interesting features and now I can see some scenarios where only 1 item needs to be selected.

Will add this feature asap (but not soon).
Thank you for the feedback.

**Comment by djclarkson** [comment]
+1 for this

**Comment by guillermomuntaner** [comment]
Feel free to add this feature and push it.

**Comment by francishart** [comment]
Hi @guillermomuntaner, I have just created a pull request for this feature. Let me know if it is ok or if anything needs changing. Thanks!

https://github.com/guillermomuntaner/GMImagePicker/pull/23

**Comment by guillermomuntaner** [comment]
Added in #30
