### ISSUE TITLE
Delete an asset from recently deleted album?

### ISSUE THREAD

**Issue by harish2304** [guillermomuntaner/GMImagePicker#18]
Hi,

Using photo kit sdk,i deleted photos from album but i can't delete them permanently as i see them getting stored in recently deleted album and the memory is not freed up.How can we delete photos from recently deleted album?
Any help is appreciated?
Thanks in advance...

**Comment by guillermomuntaner** [comment]
I think you can't. Recently deleted keeps a copy for 30days or until the user removes the photos.
