### ISSUE TITLE
Resources missing with cocoapod

### ISSUE THREAD

**Issue by top2tech** [guillermomuntaner/GMImagePicker#20]
Using cocoapod to install GMImagePicker, it works except the resources are missing. e.g. "Done" button is shown as "picker.navigation.done-button"

If not using cocoapod, and directly copy GMImagePicker into project, the resources are working properly, so looks like it's related to cocoapod only.

**Comment by guillermomuntaner** [comment]
This should be fixed by recent commit.

**Comment by Petter-W** [comment]
I just installed this with CocoaPods (pod 'GMImagePicker', '~> 0.0.1') and I manually had to add a lproj-folders.
