### ISSUE TITLE
How to set a max number for selecting photos?

### ISSUE THREAD

**Issue by WowPeter** [guillermomuntaner/GMImagePicker#24]
As you can see the title,
I'd like to set a limit(maximum) number for selecting photos.
Thanks,

**Comment by guillermomuntaner** [comment]
You can do it implementing the GMImagePickerControllerDelegate protocol method ```shouldSelectAsset``` . This method will be triggered each time user tryes to select and asset, so when they reach your limit, you can return NO to prevent the selection and display your custom alert message or w/e you want.

```
/**
 *  Asks the delegate if the specified asset should be selected.
 *
 *  @param picker The controller object managing the assets picker interface.
 *  @param asset  The asset to be selected.
 *
 *  @return `YES` if the asset should be selected or `NO` if it should not.
 *
 */
- (BOOL)assetsPickerController:(GMImagePickerController *)picker shouldSelectAsset:(PHAsset *)asset;
```

You can get the current number of selected assets from ```NSMutableArray *selectedAssets```, or you can count them yourself using ```didSelectAsset``` and ```didDeselectAsset``` protocol methods.

**Comment by guillermomuntaner** [comment]
By the way, i know these optional protocol methods are not documented and it is not trivial. If you want to improve documentatio
