### ISSUE TITLE
Latest version on Cocoapods?

### ISSUE THREAD

**Issue by olivierlesnicki** [guillermomuntaner/GMImagePicker#25]
Is it possible to update the podspec accordingly?

**Comment by guillermomuntaner** [comment]
Closed due inactivity

**Comment by Urkman** [comment]
Why this is closed?
Cocoapods still installs a version from Jan 2015...

**Comment by guillermomuntaner** [comment]
It was closed because at that date there was no significant updates. Will work on that.

**Comment by guillermomuntaner** [comment]
Uploaded latest changes to cocoapods as verison 0.0.2
