### ISSUE TITLE
Disclosure triangle is positioned incorrectly on iPad in landscape orientations

### ISSUE THREAD

**Issue by dchengTSC** [guillermomuntaner/GMImagePicker#26]
I expected the disclosure indicator to be all the way to the right as opposed to partially to the left, as shown below:

![2015-10-08_12-49-31](https://cloud.githubusercontent.com/assets/2083945/10373408/33f32332-6dbb-11e5-87d8-31b05eb220a7.png)

Strangely, it seems to work fine on the iPhone in all orientations.

This occurs with Xcode 7.0 and iOS 9 (both simulator and device).

**Comment by guillermomuntaner** [comment]
Not sure whats going on. On the iPad the recommended setup is using it as a popover and it should work fine. I've never tryed to use it full screen on an iPad, and haven't tested for iOS9, so i'm not sure what is causing this problem.

If you wanna use it fullscreen and you fix this issue, feel free to PR.

Sorry and ty!

**Comment by dchengTSC** [comment]
Good point about using it as a popover. We decided to do just that, thanks!
