### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by youhwanJeon** [guillermomuntaner/GMImagePicker#27]
Hi..
I'm just add GMImagePicker in my test project, and launch GMImagePicker -> AlbumView(select Videos) -> video GridView -> back -> back.
But, memory doesn't released 
Before launching GMImagePicker, memory usage 3.2M ,
after launching GMImagePicker and dismiss it, memory usage 7.1 ~ 7.5M
(My env :  iPhone5 IOS9.0.2 , Xcode7.0.1 , Swift 2.0)
Please check it.. thank you
![2015-10-20 20 34 25](https://cloud.githubusercontent.com/assets/6168133/10606167/ca0b231a-776b-11e5-93aa-9df3501193b9.png)

**Comment by guillermomuntaner** [comment]
Can you do exactly the same but using Apple default imagepicker? Ty.

**Comment by youhwanJeon** [comment]
Im using Apple imagePicker as you said, the same issue occurred (up to 8.9M)

so..Its just Apple's bug? Maybe, is there a way to fix it? or Please give me any hints 

thank you.

**Comment by guillermomuntaner** [comment]
I'm not sure and i cannot check. I assume this is the normal behaviour of the IOS Photo framework. This memory probably contains the image miniatures. If you open again the picker they should load faster.

I don't think you should worry at all. Probably it will be realeased when the device has memory issues.
