### ISSUE TITLE
When i go to the GMImagePickerController 

### ISSUE THREAD

**Issue by maheshm504** [guillermomuntaner/GMImagePicker#29]
when am selecting image you are showning the "1 photo selected" or some thing in the toolbartitle

so what i want is we have to show the selected image and make them add 

is this possible with this sdk

Thanks for the Good sample

**Comment by guillermomuntaner** [comment]
Sorry, i do not understand you. You mean you want to show selected images in the toolbar?

This is not supported but you can customize it by digging in the code and modifying it to your needs. I doubt you will find any library support such a specific think so probably you are going to need to implement it by youself.

**Comment by maheshm504** [comment]
Yaa the same i want

Okay i will try
ᐧ
