### ISSUE TITLE
Cocoa pods Error

### ISSUE THREAD

**Issue by modLX4** [guillermomuntaner/GMImagePicker#32]
<img width="953" alt="screen shot 2015-12-19 at 4 31 04 pm 1" src="https://cloud.githubusercontent.com/assets/12533332/11912661/f855c366-a66d-11e5-95e4-e2b948fac07b.png">

Theres is an error poping up while pod install

**Comment by guillermomuntaner** [comment]
Read the error message. 
This library requires IOS 8 and Xcode 6. Think you don't met the requirement.
