### ISSUE TITLE
PHAssetCollectionSubtypeAlbumMyPhotoStream dont show up

### ISSUE THREAD

**Issue by vitalrum** [guillermomuntaner/GMImagePicker#35]

**Comment by guillermomuntaner** [comment]
As documentations describes, you can specify the collections you want to show 

    //You can pick the smart collections you want to show:
    _customSmartCollections = @[@(PHAssetCollectionSubtypeSmartAlbumFavorites),
                                @(PHAssetCollectionSubtypeSmartAlbumRecentlyAdded),
                                @(PHAssetCollectionSubtypeSmartAlbumVideos),
                                @(PHAssetCollectionSubtypeSmartAlbumSlomoVideos),
                                @(PHAssetCollectionSubtypeSmartAlbumTimelapses),
                                @(PHAssetCollectionSubtypeSmartAlbumBursts),
                                @(PHAssetCollectionSubtypeSmartAlbumPanoramas)];
    ...

**Comment by pgeyman** [comment]
Hi,
The "My Photo Stream" collection does not show up. If you add the flag as described above it does not make any difference. I think it only works if you set the type to PHAssetCollectionTypeAlbum.
