### ISSUE TITLE
Don't display empty albums/smart albums (or display them optionally)

### ISSUE THREAD

**Issue by guillermomuntaner** [guillermomuntaner/GMImagePicker#5]
Check number of items in collections and don't display them in albums list if empty. Another idea is to add customisable delegate method so user can set the condition to display or not albums (maybe he don't want to display X album, or empty albums, or albums with less than X items, etc...)

**Comment by olivierlesnicki** [comment]
@guillermomuntaner empty albums still display when mediaTypes is set to something specific
