### ISSUE TITLE
Content visible scrolling behind the status bar and not the navigation bar

### ISSUE THREAD

**Issue by pgeyman** [guillermomuntaner/GMImagePicker#52]
When scrolling content in the album list or the photos grid, the content is clearly visible scrolling behind the status bar, but the navigation bar is opaque and so it looks terrible.

Please provide a way to extend the navigation bar behind the status bar
or allow setting _navigationController.navigationBar.translucent = NO

**Comment by derpoliuk** [comment]
```Objective-C
GMImagePickerController *picker = [[GMImagePickerController alloc] init];
picker.navigationController.navigationBar.translucent = NO;
```

**Comment by derpoliuk** [comment]
@guillermomuntaner I think you can close this issue now.
