### ISSUE TITLE
Already Select

### ISSUE THREAD

**Issue by vishaldeshai** [guillermomuntaner/GMImagePicker#69]
Hello,

If i selected 5 photos from gallery and done. and we need to select those photo previous again by default selected.

Is it possible.

Thanks in advance.

**Comment by guillermomuntaner** [comment]
Yes it is possible and is documented. Always try to read interfaces for further documentation!
```
/**
 *  It contains the selected `PHAsset` objects. The order of the objects is the selection order.
 *
 *  You can add assets before presenting the picker to show the user some preselected assets.
 */
@property (nonatomic, strong) NSMutableArray *selectedAssets;
```
