### ISSUE TITLE
This library should be updated or deprecated

### ISSUE THREAD

**Issue by hammadzz** [guillermomuntaner/GMImagePicker#71]
It uses https://github.com/gmoledina/GMGridView which has crashes but is no longer being maintained as iOS introduced UICollectionView. So either this library should be updated or deprecated so people don't get stuck using code that isn't being maintained.

**Comment by volodymyr-vestasoft** [comment]
Same here, I just tried to use it and got crashes: "Terminated due to memory issue". 
Is anyone knows how to fix this maybe?

**Comment by hammadzz** [comment]
Delete the library and use something else.

**Comment by volodymyr-vestasoft** [comment]
I like that because its simple and easy to install. I'm not using pods.

**Comment by guillermomuntaner** [comment]
This library has nothing to do with GMGridView, it is just a name coincidence (i guess same initials). Not sure how you arrived to that conclusion, since there is no dependency whatsoever and if you check the source you can see I am subclassing apples UIKit. 
```
@interface GMGridViewCell : UICollectionViewCell
@interface GMGridViewController : UICollectionViewController
```
