### ISSUE TITLE
Crashing on IOS 10

### ISSUE THREAD

**Issue by BillyJohn3** [guillermomuntaner/GMImagePicker#78]
Hey, I'm having a lot of trouble with this crashing for some users on IOS10.
Below is my code which checks the permissions before loading the picker but users are saying that the app is crashing after selecting a few videos or just after loading the picker. I can't replicate on my machine but wonder if this is related to the changes in UIImageCollection made recently?

Please give me any ideas! I really need to get this fixed ASAP.

`- (IBAction)selectPhotos:(id)sender {
    
    PHAuthorizationStatus status = [PHPhotoLibrary authorizationStatus];//checks if authorized to access
    
    if (status == PHAuthorizationStatusAuthorized) {//is authorised to access
        GMImagePickerController *picker = [[GMImagePickerController alloc] init];
        picker.delegate = self;
        
        picker.title = @"Upload";
        picker.customNavigationBarPrompt = @"Select photos and videos to upload";
        picker.minimumInteritemSpacing = 1.0;
        
        [self presentViewController:picker animated:YES completion:nil];
    }
    
    else if (status != PHAuthorizationStatusAuthorized) {// if not authorised
        UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Access denied" message:@"You've previously denied access to your photos so please go to settings and allow access." delegate:self cancelButtonTitle:@"Cancel" otherButtonTitles:@"Change settings", nil];
        [alert show];
    }
}`

**Comment by BillyJohn3** [comment]
I'm currently working on this being an icloud issue. I see that the phassets are requested without networkaccessallowed. So I'm going to try changing the request options to allow for items in icloud and seeing if this fixes.

**Comment by lorenzoPrimi** [comment]
Any news about this? @BillyJohn3 
I get crashes when selecting icloud photos.

**Comment by BillyJohn3** [comment]
Yes @lorenzoPrimi 
The problem is that the photos are not stored on the iPhone so you need to allow the phone to download them. You do this using PHRequestOptions networkaccess.allowed

Do a search for RequestImageForAsset and each will be requested with an 'options' input.
If options == nill then create a set of options ('PHImageRequestOptions') and then edit the options using: 
PHImageRequestOptions *options = [PHImageRequestOptions new];
options.networkAccesssAllowed = yes;
and then use those options in the request funtion

and if it has options already there just amend the options by adding the second line:
options.networkAccesssAllowed = yes;

This fixed for me. Should sort it

**Comment by lorenzoPrimi** [comment]
I was looking on github and I implemented it like this
`        PHImageRequestOptions* options = [[PHImageRequestOptions alloc] init];
        options.synchronous = NO;
        options.version = PHImageRequestOptionsVersionCurrent;
        options.deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic;
        options.resizeMode = PHImageRequestOptionsResizeModeNone;
        options.networkAccessAllowed = YES;
`
do you think it's better?

**Comment by BillyJohn3** [comment]
Up to you. I didn't need all those extra options I just needed it to allow network access.
