### ISSUE TITLE
Label text is wrong

### ISSUE THREAD

**Issue by albertbori** [guillermomuntaner/GMImagePicker#8]
The appropriate language isn't populating into the various labels. Instead, it just shows the keys for each label. (Installed using CocoaPods 0.36.0)

Edit: This only occurs when the Podfile declares: `use_frameworks!`

![ios simulator screen shot mar 28 2015 11 41 15 am](https://cloud.githubusercontent.com/assets/1742709/6882368/8a793ddc-d53f-11e4-83c5-a3a5f32e0f71.png)

**Comment by vitalrum** [comment]
just find GMImagePicker.strings in demo project and add this in your project

**Comment by guillermomuntaner** [comment]
#14 Merged. Thank you.
